### ISSUE TITLE
keras-contrib pull request

### ISSUE THREAD

**Issue by ahundt** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#8]
Once #7 is committed and verified to work with theano, I'm hoping to look at extending your keras-contrib [densenet.py](https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/applications/densenet.py) submission to support densenet-fcn as well.

Would that be okay with you?

I'll plan to also include a conversion script for pascal_voc.

**Comment by titu1994** [comment]
I actually feel that the core DenseNet for classification and DenseNet for semantic segmentation should be separate. 

The idea is different, one is for classification and another is for semantic segmentation. While they use DenseNets, semantic segmentation has a very different form to ordinary DenseNets. 

That is why I have separated this repository from the pure densenet model builder repo, because the ideas behind them are different. It does not make sense to shoehorn semantic segmentation model creation code into DenseNet creation code.

**Comment by ahundt** [comment]
The purposes are definitely different, but the differences are still kind of small though.

If I read things correctly the only differences are:
- rename transition_block transition_down_block
- add transition_up_block (plus optional alternative upsampling layers)
- add create_dense_net_fcn()
- add flag for fcn options to DenseNet class

**Comment by ahundt** [comment]
I mean it can also be in a separate DenseNetFCN class that imports DenseNet. That's easy enough, though I think a single class may be more sensible.

**Comment by titu1994** [comment]
Yes a class DenseNetsFCN which imports DenseNet sounds better. 

It may be my bias, but I tend to keep projects with different end goals completely separate, so as to avoid overcomplicating either project. 

Importing core methods from DenseNet and adding the necessary additional methods to build the DenseNetFC sound like a good idea. 

Would you do it or should I? Since it's your idea I feel like you should add the PR to Keras contrib but I'm OK with anything.

**Comment by ahundt** [comment]
sure I can do it, it will be a while because I need to implement a converter from raw pascal_voc to a keras model setup so I can submit a dataset alongside the semantic segmentation code to train from.

some conversion stuff:
https://github.com/ahundt/tf-image-segmentation/blob/ahundt-keras/tf_image_segmentation/recipes/pascal_voc/convert_pascal_voc_to_tfrecords.ipynb
https://github.com/martinkersner/train-DeepLab

request for license permission:
https://github.com/martinkersner/train-DeepLab/issues/23

**Comment by titu1994** [comment]
Cool I'll leave it to you then. 

I'm quite a bit tied up in assignments and midterms so I won't be as active for the next week or so.
